var genero = prompt ("Eres Hombre o Mujer?");
var Estilo = prompt ("Estilo formal o informal?");
var Clima = prompt ("Para frio o calor?");
var Caracter = prompt ("Eres introvertido o extrovertido?");
var anime = prompt ("te gusta el anime?");


if (genero == "Hombre" || "hombre" ) 
{

    if (Estilo == "formal") 
    {

        if (Clima == "frio") 
        {

            if (Caracter == "introvertido")
            {
                if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");}  
                
            else if (Caracter == "extrovertido")
                {
                if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                }
                 
        else if (Clima == "calor") 
              {
                if (Caracter == "introvertido")
                {
                        if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                        else if  (anime =="no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 

                else if (Caracter == "extrovertido")
                    {
                        if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                        else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");}
                    }
                }               
              }
            }
        }

    else if (Estilo == "informal")
    {

        if (Clima == "frio") 
        {

            if (Caracter == "introvertido")
            {
                if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");}  
                
            else if (Caracter == "extrovertido")
                {
                if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                else if  (anime = "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                }
                 
        else if (Clima == "calor") 
              {
                if (Caracter == "introvertido")
                {
                        if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                        else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 

                else if (Caracter == "extrovertido")
                    {
                        if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                        else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");}
                    }
                }               
              }
            }
        }  

    } 
    
    }

} 










if (genero == "Mujer" || "mujer" ) 
{

    if (Estilo == "formal") 
    {

        if (Clima == "frio") 
        {

            if (Caracter == "introvertido")
            {
                if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");}  
                
            else if (Caracter == "extrovertido")
                {
                if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                }
                 
        else if (Clima == "calor") 
              {
                if (Caracter == "introvertido")
                {
                        if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                        else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 

                else if (Caracter == "extrovertido")
                    {
                        if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                        else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");}
                    }
                }               
              }
            }
        }
        
    else if (Estilo == "informal")
    {

        if (Clima == "frio") 
        {

            if (Caracter == "introvertido")
            {
                if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");}  
                
            else if (Caracter == "extrovertido")
                {
                if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                }
                 
        else if (Clima == "calor") 
              {
                if (Caracter == "introvertido")
                {
                        if (anime == "si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                        else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 

                else if (Caracter == "extrovertido")
                    {
                        if (anime =="si"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");} 
                        else if  (anime == "no"){document.write("<img scr='https://otakus.space/wp-content/uploads/2021/10/ropa-otaku-mujer-1.jpg.webp' >");}
                    }
                }               
              }
            }
        }  

    } 
    
    }

} 